
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jul 21 14:37:24 CEST 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUALSTO = 29;
  public static final int PLUSPLUS = 38;
  public static final int MAP = 23;
  public static final int CHAR = 53;
  public static final int CONST = 8;
  public static final int CASE = 21;
  public static final int LPAREN = 44;
  public static final int SEMI = 41;
  public static final int GREATER = 31;
  public static final int CONTINUE = 16;
  public static final int LESS = 33;
  public static final int FOR = 17;
  public static final int MINUS = 25;
  public static final int RPAREN = 45;
  public static final int AND = 35;
  public static final int OR = 36;
  public static final int BOOL = 52;
  public static final int COMMA = 42;
  public static final int ELESS = 34;
  public static final int CLASS = 5;
  public static final int DOUBLEDOT = 51;
  public static final int DIV = 27;
  public static final int DIFFERENT = 30;
  public static final int PLUS = 24;
  public static final int IF = 9;
  public static final int LSQBRACE = 48;
  public static final int DOT = 43;
  public static final int FINDANY = 22;
  public static final int ABSTRACT = 6;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 39;
  public static final int RETURN = 13;
  public static final int EQUAL = 37;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int NUMBER = 54;
  public static final int EGREATER = 32;
  public static final int MOD = 28;
  public static final int IDENT = 55;
  public static final int BREAK = 3;
  public static final int VOID = 14;
  public static final int SWITCH = 20;
  public static final int ARROW = 40;
  public static final int FOREACH = 18;
  public static final int LBRACE = 46;
  public static final int ELSE = 7;
  public static final int ENUM = 4;
  public static final int READ = 12;
  public static final int RBRACE = 47;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int QUESTION = 50;
  public static final int RSQBRACE = 49;
  public static final int PRINT = 11;
  public static final int LENGTH = 19;
}

